name: Release
run-name: Create release by ${{ github.actor }}
on:
  push:
    tags:
      - '20*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - if: ${{ env.ACT_LOCAL_TEST == '1' }}
        working-directory: ${{ github.workspace }}
        run: bash ./build.sh

      - if: ${{ env.ACT_LOCAL_TEST != '1' }}
        run: sudo --preserve-env=ACT_LOCAL_TEST,DOWNLOAD_BASE_URL,COMPRESS_OUTPUT bash build.sh

      - if: ${{ env.ACT_LOCAL_TEST == '1' }}
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ${{ github.workspace }}/output

      - if: ${{ env.ACT_LOCAL_TEST != '1' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.xz"
